### ISSUE TITLE
corpus 구성 방법 문의

### ISSUE THREAD

**Issue by amazingguni** [kh-kim/simple-ntc#1]
`자연어 처리 딥러닝 캠프`를 읽으며 많은 도움을 받고 있는 독자입니다 
텍스트 분류 코드를 구동시켜 보려는데 corpus를 구성하는 방법을 알지 못해 문의드립니다.
README를 보면 클리앙 등의 커뮤니티의 글로 구성되어 있는 것으로 보이는데,
train/validate set을 구성할 수 있는 방법을 알 수 있을까요?

**Comment by kh-kim** [comment]
안녕하세요.

이슈 확인이 늦어 죄송합니다.
저는 아래의 레포의 소스코드를 활용하여 클리앙의 게시물들을 크롤링 하였고, 
이를 텍스트 분류에 적용하여 보았습니다.

https://github.com/kh-kim/clien_crawler

감사합니다.
