### ISSUE TITLE
I need to get test corpus

### ISSUE THREAD

**Issue by ynebula** [kh-kim/simple-ntc#3]
I bought your book.

I try to do test source.

so I need test corpus.

please let me know way to get corpus

**Comment by kh-kim** [comment]
안녕하세요, 늦게 이슈를 보게되어 죄송합니다.
제가 온라인 강의 수강생분들을 위해 코퍼스를 배포하기 위해 작업하고 있는데, nlp.with.deep.learning@gmail.com 으로 메일 주시면 수일내로 코퍼스를 제공해드리겠습니다.
